In [19]:
import pandas as pd
import numpy as np
import pickle
import tensorflow as tf
from tensorflow import keras
from keras.models import Model
from keras.layers import GlobalMaxPooling2D
from keras.layers import GlobalAveragePooling2D
from keras.preprocessing import image
from keras.layers import Input,Conv2D, MaxPool2D, Flatten, Dense, Activation, Dropout,MaxPooling2D
from keras.models import Sequential
from tensorflow.keras.optimizers import Adam

In [6]:
with open('train_X.pkl','rb') as f:
    train_X = pickle.load(f)
    print(train_X.shape)
    
with open('train_Y.pkl','rb') as f:
    train_Y = pickle.load(f)
    print(train_Y.shape)
    
with open('test_X.pkl','rb') as f:
    test_X = pickle.load(f)
    print(test_X.shape)
    
with open('test_Y.pkl','rb') as f:
    test_Y = pickle.load(f)
    print(test_Y.shape)
    
with open('pred_data.pkl','rb') as f:
    pred_data = pickle.load(f)
    print(pred_data.shape)

(14034, 150, 150, 3)
(14034,)
(3000, 150, 150, 3)
(3000,)
(7301, 150, 150, 3)


In [20]:
def VGGupdated(input_tensor=None,classes=6):    
   
    img_rows, img_cols = 150, 150   # by default size is 224,224
    img_channels = 3

    img_dim = (img_rows, img_cols, img_channels)
   
    img_input = Input(shape=img_dim)
    
    # Block 1
    x = Conv2D(64, (3, 3), activation='relu', padding='same', name='block1_conv1')(img_input)
    x = Conv2D(64, (3, 3), activation='relu', padding='same', name='block1_conv2')(x)
    x = MaxPooling2D((2, 2), strides=(2, 2), name='block1_pool')(x)

    # Block 2
    x = Conv2D(128, (3, 3), activation='relu', padding='same', name='block2_conv1')(x)
    x = Conv2D(128, (3, 3), activation='relu', padding='same', name='block2_conv2')(x)
    x = MaxPooling2D((2, 2), strides=(2, 2), name='block2_pool')(x)

    # Block 3
    x = Conv2D(256, (3, 3), activation='relu', padding='same', name='block3_conv1')(x)
    x = Conv2D(256, (3, 3), activation='relu', padding='same', name='block3_conv2')(x)
    x = Conv2D(256, (3, 3), activation='relu', padding='same', name='block3_conv3')(x)
    x = MaxPooling2D((2, 2), strides=(2, 2), name='block3_pool')(x)
    
    # Block 4
    x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block4_conv1')(x)
    x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block4_conv2')(x)
    x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block4_conv3')(x)
    x = MaxPooling2D((2, 2), strides=(2, 2), name='block4_pool')(x)

    # Block 5
    x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block5_conv1')(x)
    x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block5_conv2')(x)
    x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block5_conv3')(x)
    x = MaxPooling2D((2, 2), strides=(2, 2), name='block5_pool')(x)

    
    # Classification block
    x = Flatten(name='flatten')(x)
    x = Dense(4096, activation='relu', name='fc1')(x)
    x = Dense(4096, activation='relu', name='fc2')(x)
    x = Dense(classes, activation='softmax', name='predictions')(x)

    # Create model.
   
     
    model = Model(inputs = img_input, outputs = x, name='VGGdemo')


    return model

In [21]:
model = VGGupdated(classes = 6) 

In [22]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [24]:
train_X.shape

(14034, 150, 150, 3)

In [143]:
train_features=train_X[0:1000,]
train_labels=train_Y[0:1000,]

In [144]:
test_features=train_X[0:50,]
test_labels=train_Y[0:50,]

In [146]:
train_features.shape

(1000, 150, 150, 3)

In [147]:
model.fit(train_features, train_labels, epochs = 10, batch_size = 32)

Epoch 1/10
32/32 [==============================] - 211s 7s/step - loss: 1.7922 - accuracy: 0.1810
Epoch 2/10
32/32 [==============================] - 255s 8s/step - loss: 1.7897 - accuracy: 0.1810
Epoch 3/10
32/32 [==============================] - 215s 7s/step - loss: 1.7895 - accuracy: 0.1810
Epoch 4/10
32/32 [==============================] - 215s 7s/step - loss: 1.7896 - accuracy: 0.1640
Epoch 5/10
32/32 [==============================] - 242s 8s/step - loss: 1.7893 - accuracy: 0.1810
Epoch 6/10
32/32 [==============================] - 260s 8s/step - loss: 1.7893 - accuracy: 0.1640
Epoch 7/10
32/32 [==============================] - 262s 8s/step - loss: 1.7893 - accuracy: 0.1820
Epoch 8/10
32/32 [==============================] - 266s 8s/step - loss: 1.7894 - accuracy: 0.1810
Epoch 9/10
32/32 [==============================] - 266s 8s/step - loss: 1.7891 - accuracy: 0.1810
Epoch 10/10
32/32 [==============================] - 273s 9s/step - loss: 1.7894 - accuracy: 0.1810


In [148]:
# y_pred = model.predict('forest.jpg')
y_pred = model.predict(test_features)

In [152]:
y_pred[0]

array([0.16612653, 0.14600784, 0.18014352, 0.17788975, 0.16894588,
       0.16088642], dtype=float32)

In [149]:
# x=y_pred[1]

y_pred_new = []
for i in range (0, len(y_pred)):
    z = max(y_pred[i])
    n = np.where(y_pred[i] == z)
    p =n[0]
    y_pred_new.append(p)


In [150]:
y_pred_new

[array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], 

In [139]:
# test_labels[8] == y_pred_new[8]
test_labels

array([0, 0, 5, 4, 3, 3, 4, 5, 2, 0, 5, 2, 2, 4, 2, 5, 5, 4, 0, 0, 0, 4,
       0, 5, 5, 0, 5, 4, 3, 0, 2, 0, 1, 0, 3, 0, 1, 4, 4, 1, 3, 4, 2, 4,
       0, 2, 0, 3, 1, 5])

In [134]:
test_loss, test_acc = model.evaluate(test_features,  test_labels, verbose=2)

2/2 - 2s - loss: 1.8167 - accuracy: 0.1400
